### ISSUE TITLE
Urza lands wrong rarity in Master Edition IV

### ISSUE THREAD

**Issue by JayDi85** [scryfall/gatherer-bugs#34]
Some Urza's lands have different rarity in scryfall and gatherer.

Generally all [urzas cards are non basic lands](https://mtg.gamepedia.com/Urza%27s). Scryfall show rarity fine. BUT gatherer use "basic land" rarity in Master Edition IV and common/uncommon rarity in other.

Wrong sets on gatherer:
 * Masters Edition IV ([example](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=220955));

![shot_180927_122114](https://user-images.githubusercontent.com/8344157/46132729-ec738a00-c24f-11e8-97be-c96c66dad494.png)

**Comment by silasary** [comment]
This is correct. 

The Urza's lands were in the basic land slot in ME4.

> Each booster pack contains 15 randomly sorted cards (1 rare, 3 uncommon, 10 common, and 1 of the following lands: Urza's Mine, Urza's Power Plant, or Urza's Tower).

https://magic.wizards.com/en/game-info/products/card-set-archive/masters-edition-iv

**Comment by JayDi85** [comment]
It's in basic slot for booster, but it't not the basic land itself. E.g. you can't use it in any format as basic land rules (4+ cards per deck).

![shot_180927_160820](https://user-images.githubusercontent.com/8344157/46144978-a3cbc900-c26f-11e8-91de-0ea4e36cf6de.png)


![shot_180927_160940](https://user-images.githubusercontent.com/8344157/46145026-d4abfe00-c26f-11e8-9468-ba4985df9320.png)

**Comment by csuhta** [comment]
@JayDi85 The Uzra lands are not basic lands, but this isn't what "Basic Land" rarity on Gatherer means here. It is WotC's notation for appearing in the basic land slot of a booster. It usually makes the card even more "common" than common cards. 

Newer cards with this rarity have "L" on the bottom of the card, but Scryfall files those cards under commons since most people don't make this really specific distinction.
