### ISSUE TITLE
Incorrect escaped name for ZNR card 22

### ISSUE THREAD

**Issue by StevenDeBock** [scryfall/gatherer-bugs#85]
https://api.scryfall.com/cards/znr/22
feels to have an incorrectly escaped "name" element, i.e.:
	"name": "\"Cleric of Raves\"",
when comparing with card #11, I have:
	"name": "Emeria Captain",

-- Let me know if this needs a gatherer bug since I'm not sure if this is a pure scryfall bug or a gatherer bug, I didn't create a bug on gatherer.

**Comment by csuhta** [comment]
Hey there: This card's name is in quotes because it is a joke translation while we await the real name from WotC.

The quotes seem properly escaped here, are you perhaps parsing them differently in your local code? https://api.scryfall.com/cards/znr/22?pretty=true

Also: This repo is for publicly discussing issues on Gatherer that we have filed with WotC. Please use Scryfall's contact form to report issues with Scryfall or ask questions https://scryfall.com/contact
